spring:
  batch:
    job:
      name: ${job.name}
#      enabled: false
    jdbc:
      initialize-schema: always
  jpa:
    hibernate.ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 500
        dialect: org.hibernate.dialect.MySQLDialect
    open-in-view: false
  datasource:
    url: jdbc:mysql://localhost:3306/shop
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

logging:
  level:
    org:
      hibernate:
        SQL: debug
        type: info
